spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/app_machine_sentinel?currentSchema=dev
spring.datasource.username=${MACHINE_SENTINEL_ROLE_DEV:app_machine_sentinel_dev}
spring.datasource.password=${MACHINE_SENTINEL_ROLE_DEV_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.schemas=dev
spring.flyway.default-schema=dev
